version: '3'

services:
  api:
    build: .
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:80"
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - postgres
      - migration
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static

  postgres:
    image: postgres
    restart: on-failure
    container_name: postgres_al
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  migration:
    build: .
    container_name: migration_al
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --noinput"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

volumes:
  postgres_data:
  static_volume: